---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: check-case-conflict
      # - id: check-executables-have-shebangs
      # - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      # - id: detect-aws-credentials
  # CICD ####################################################################
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.26.1
    hooks:
      - id: check-github-workflows
  # ANSIBLE ####################################################################
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v6.18.0
    hooks:
      - id: ansible-lint
        args: ['-c', '.ci/ansible-lint']
  # - repo: https://github.com/markdownlint/markdownlint
  #   rev: f6d205a9bc118723f52e3242faebc58f9b46fd72
  #   hooks:
  #     - id: markdownlint_docker
  # PYTHON #####################################################################
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        exclude: files/mods_by_kllw538/
        args: ['--config', './pyproject.toml']
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ['--config', '.ci/flake8']
  # DOCKER #####################################################################
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
      - id: hadolint-docker
        args: ['-c', '.ci/hadolint.yaml']
  # - id: hadolint
  # DATA FILES #################################################################
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: ['-c=.ci/yamllint']
  # SHELL ######################################################################
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
      - id: shfmt
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.22
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
  # COMMITIZEN #################################################################
  - hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.7.0
