---
# Update system  Ubuntu
- name: Update System cache [Common, Debian family]
  apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 3600
  tags:
    - update_system

- name: Kill apt
  command: killall apt apt-get
  register: kill
  changed_when: kill.rc != 2

- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
