---
# Update system  Ubuntu
- name: Reboot after system have been deployed
  reboot:
    reboot_timeout: 100

- name: Update System cache [Common, Debian family]
  apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400
  register: updatest
  ignore_errors: true
  tags:
    - update_system

- name: Run dpkg if needed
  command: 'dpkg --configure -a'
  register: dpkgst
  changed_when: dpkgst.rc != 2
  when: updatest.failed

- name: Find stuck apt procs
  command: pgrep apt
  register: aptprocs
  ignore_errors: true
  changed_when: false

- name: Kill apt
  command: killall apt apt-get
  register: kill
  changed_when: kill.rc != 2
  ignore_errors: true
  when: aptprocs.rc = 0

- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
