---
- name: Create airflow group
  group:
    name: "{{ groupname }}"
    state: present
    gid: "{{ AIRFLOW_GUID }}"

- name: Create airflow user
  user:
    name: "{{ username }}"
    groups: airflow,docker
    uid: "{{ AIRFLOW_UID }}"

- name: Create directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: '0777'
    recurse: true
  loop:
    - "{{ data_path }}/dags"
    - "{{ data_path }}/logs"
    - "{{ data_path }}/config"
    - "{{ data_path }}/plugins"

- name: Copy Dags
  copy:
    src: files/
    dest: "{{ data_path }}/dags"
    mode: '0777'
    owner: "{{ username }}"
    group: "{{ groupname }}"

- name: Template system var
  template:
    src: airflow.sh.j2
    dest: /etc/profile.d/airflow.sh
    mode: '0777'
    owner: root
    group: root

- name: Create db directory
  file:
    path: "{{ db_path }}"
    state: directory
    mode: '0777'

- name: Template seed file
  template:
    src: dbseed.sql.j2
    dest: "{{ db_path }}/dbseed.sql"
    mode: '0777'
    owner: "{{ username }}"
    group: "{{ groupname }}"

- name: Reboot VM
  reboot:
    reboot_timeout: 120
