---
- name: Create directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0600'
  loop:
    - "{{ install_path }}/dags"

- name: Templating docker compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ install_path }}"
    mode: '0600'
    owner: root
    group: root
