---
name: Destroy
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      job_environment:
        type: choice
        description: 'Job environment prod or dev'
        required: true
        default: 'dev'
        options:
          - dev
          - prod

env:
  image_name: airflow
  repo: ghcr.io
  job_environment: dev

jobs:
  Checkout_repos:
    runs-on:
      - self-hosted
    container:
      image: hashicorp/terraform:latest
      env:
        DIGITALOCEAN_TOKEN: ${{ secrets.DO_TOKEN }}
        aws_access_key: ${{ secrets.DO_S3_ID }}
        aws_secret_key: ${{ secrets.DO_S3_KEY }}
        environment: ${{ github.event.inputs.job_environment }}
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Terraform Init
        id: init
        run: make init

      - name: Select workspace
        run: make workspace

      - name: Terraform Destroy
        id: destr
        run: make destroy
