---
name: Destroy
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      job_environment:
        type: choice
        description: 'Job environment prod or dev'
        required: true
        default: 'dev'
        options:
          - dev
          - prod
      confirm:
        description: |
          Please confirm this action with this message: 'confirm'
        required: true

env:
  image_name: airflow
  repo: ghcr.io
  job_environment: dev

jobs:
  Destroy:
    if: github.event.inputs.confirm == 'confirm'
    runs-on:
      - self-hosted
    container:
      image: hashicorp/terraform:1.6.5
      env:
        DIGITALOCEAN_TOKEN: ${{ secrets.DO_TOKEN }}
        aws_access_key: ${{ secrets.DO_S3_ID }}
        aws_secret_key: ${{ secrets.DO_S3_KEY }}
        environment: ${{ github.event.inputs.job_environment }}
    steps:
      - name: Install make
        # yamllint disable-line rule:line-length
        run: apk add --no-cache make && wget https://github.com/cloudposse/tfmask/releases/download/0.7.0/tfmask_linux_amd64 -O /usr/bin/tfmask && chmod 755 /usr/bin/tfmask

      - name: Checkout current repo
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Terraform Init
        id: init
        run: make init

      - name: Select workspace
        run: make workspace

      - name: Terraform Destroy
        id: destr
        run: make destroy
