---
name: Pre-commit
run-name: "Code validation [attempt: #${{ github.run_attempt }}]"

# yamllint disable-line rule:truthy
on:
  # yamllint disable-line rule:empty-values
  push:
    branches:
      - '**'
      - '!master'
      - '!main'
      - '!refs/pull/*'

jobs:
  pre-commit:
    runs-on:
      - self-hosted
    container:
      image: ubuntu:latest
      env:
        registry-username: ${{ secrets.DOCKER_USERNAME }}
        registry-password: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Pre config
        run: apt update && apt install sqlite3 -y

      - name: Configuring Pyhton
        uses: actions/setup-python@v3

      - name: Run Pre commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args:  -c .pre-commit-config.yaml --all-files
